import type { Conversation } from './inboxTypes';

export const CONVERSATIONS: Conversation[] = [
  {
    id: 'c1',
    name: 'Rajesh Mehta',
    phone: '+91 98765 43210',
    lastMessage: 'Can we schedule a site visit for this weekend?',
    lastMessageSender: 'them',
    timestamp: '2m',
    unread: 3,
    status: 'typing',
    tags: ['NEW', 'HOT'],
    assignedTo: 'Priya',
    isBotHandled: false,
  },
  {
    id: 'c2',
    name: 'Ananya Builders',
    phone: '+91 88765 11122',
    lastMessage: 'You: Sent the brochure for Skyline Residency',
    lastMessageSender: 'me',
    timestamp: '8m',
    unread: 0,
    status: 'online',
    tags: ['VIP', 'RETURNING'],
    assignedTo: 'Arjun',
    isBotHandled: false,
  },
  {
    id: 'c3',
    name: 'Sunil Group',
    phone: '+91 99887 65432',
    lastMessage: 'Bot: I can help with pricing details!',
    lastMessageSender: 'bot',
    timestamp: '15m',
    unread: 1,
    status: 'online',
    tags: ['BOT'],
    assignedTo: 'AI Bot',
    isBotHandled: true,
  },
  {
    id: 'c4',
    name: 'Kavya Reddy',
    phone: '+91 90123 45678',
    lastMessage: 'What are the EMI options available?',
    lastMessageSender: 'them',
    timestamp: '32m',
    unread: 2,
    status: 'away',
    tags: ['NEW'],
    isBotHandled: false,
  },
  {
    id: 'c5',
    name: 'Metro Realty',
    phone: '+91 91234 56789',
    lastMessage: 'You: Great, the meeting is confirmed for 11 AM',
    lastMessageSender: 'me',
    timestamp: '1h',
    unread: 0,
    status: 'offline',
    tags: ['VIP', 'HOT'],
    assignedTo: 'Sneha',
    isBotHandled: false,
  },
  {
    id: 'c6',
    name: 'Vikram Singh',
    phone: '+91 87654 32109',
    lastMessage: 'Bot: Your appointment has been booked successfully',
    lastMessageSender: 'bot',
    timestamp: '1h',
    unread: 0,
    status: 'offline',
    tags: ['BOT', 'RETURNING'],
    assignedTo: 'AI Bot',
    isBotHandled: true,
  },
  {
    id: 'c7',
    name: 'Deepika Nair',
    phone: '+91 99876 54321',
    lastMessage: 'Is the property still available?',
    lastMessageSender: 'them',
    timestamp: '2h',
    unread: 0,
    status: 'offline',
    tags: ['NEW'],
    isBotHandled: false,
  },
  {
    id: 'c8',
    name: 'Apex Housing',
    phone: '+91 90987 65432',
    lastMessage: 'You: I will send the final quote by tomorrow',
    lastMessageSender: 'me',
    timestamp: '3h',
    unread: 0,
    status: 'offline',
    tags: ['VIP'],
    assignedTo: 'Sneha',
    isBotHandled: false,
  },
  {
    id: 'c9',
    name: 'Meera Iyer',
    phone: '+91 88123 45678',
    lastMessage: 'Thank you so much for the quick response!',
    lastMessageSender: 'them',
    timestamp: '5h',
    unread: 0,
    status: 'offline',
    tags: ['RETURNING'],
    isBotHandled: false,
  },
  {
    id: 'c10',
    name: 'Karthik Solutions',
    phone: '+91 87612 99887',
    lastMessage: 'Bot: Please share your preferred time slot',
    lastMessageSender: 'bot',
    timestamp: '6h',
    unread: 0,
    status: 'offline',
    tags: ['BOT', 'NEW'],
    assignedTo: 'AI Bot',
    isBotHandled: true,
  },
  {
    id: 'c11',
    name: 'Nisha Agarwal',
    phone: '+91 98300 11223',
    lastMessage: 'Can I get a callback from an agent?',
    lastMessageSender: 'them',
    timestamp: '8h',
    unread: 5,
    status: 'offline',
    tags: ['HOT'],
    isBotHandled: false,
  },
  {
    id: 'c12',
    name: 'Rohan Desai',
    phone: '+91 90011 22334',
    lastMessage: 'You: Shared the floor plan PDF',
    lastMessageSender: 'me',
    timestamp: '1d',
    unread: 0,
    status: 'offline',
    tags: ['RETURNING'],
    assignedTo: 'Rahul',
    isBotHandled: false,
  },
];
